### PR TITLE
Use extend module

### PR DESCRIPTION
**Pull request by RobLoach**
See http://npm.im/extend | https://github.com/justmoon/node-extend

### CODE REVIEW

**Comment by stevenschobert** [comment]
Don't like my extend function?

**Comment by RobLoach** [comment]
lol

**Comment by stevenschobert** [comment]
No, really though. Were you having any bugs/issues?

**Comment by RobLoach** [comment]
Nope! Just saw an opportunity to simplify the code... I like the function! Worthy of its own npm module :+1: . `require('extenddoneright')`?

**Comment by stevenschobert** [comment]
Think I'll keep it the way it is for now, but thanks for the suggestion! Always happy to hear more thoughts.

**Pull request closed without merging**
