### PR TITLE
Indented syntax support and compiler pass-through options

### PR DESCRIPTION
**Pull request by codemonsieur**
Hey, not a pro by any means, but I was missing some functionality and thought I'd give it a go at adding following changes:
- Added support for indented sass syntax
- Will autodetect syntax style based on extension (.scss/.sass)
- Added passthroughOptions to enable sending options directly to compiler
Hope this helps!

### CODE REVIEW

**Comment by stevenschobert** [comment]
Hey @codemonsieur! Thanks for the additions, I can tell you put a lot of effort into it! :+1: 

Since there's a good bit of stuff added here, would you mind breaking it down a little bit for me? Like what use cases you were needing, and your thoughts were for how to implement them?

It'll really help me parse through the additions and test them out! Thanks!

**Comment by codemonsieur** [comment]
Hey @stevenschobert,

Basically, I'm using the plugin as I'm working on a couple of static sites, found metalsmith a great tool for this. Personally, I'm not a big fan of the superset scss syntax and prefer to write my sass using the indented syntax, which was not supported by metalsmith-sass out of the box - the .sass files were ignored and copied into build directory untouched.

Firstly, I've changed the regex in _isSassFile_ method to include .sass files in addition to .scss when looking for sources to parse. When the .sass files are passed on to _sass.render_, they need an extra option added, which is _indentedSyntax_ - detection of whether this is necessary is taken care of by the _isIndentedSassFile_ method (which is a bit of a duplicate for the _isSassFile_, wasn't sure how to do it in a better way).

As I was writing this, as I was looking for the option within _node-sass_ docs, I thought that maybe someone would prefer to pass other options into the compiler, e.g. enabling debug comments in sass output for debugging or adjusting digit precision. The current implementation didn't allow that, which is why I added the passthrough options. After I requested the pull, I realised that this creates a bit of ambiguity as some options can be passed on in two ways now - via predefined options you have implemented, as well as directly to the compiler. Maybe it would work letting passthrough options take care of any options the user might want to send to _node-sass_, such as _outputStyle_, while metalsmith-sass' options could concentrate on plugin-specific options, such as _outputDir_. This way metalsmith-sass would not need to be adjusted if sass changes any of their options, as these would always be passed on directly.

Does this make sense? :) Sorry, it's a bit late over here, had a long day, so apologies for a long-ass answer! :) I also wasn't sure if there's a way to directly reference specific lines from the commit in here, so pardon the inline &lt;em&gt;s :)

Hope this clarifies things!

**Comment by stevenschobert** [comment]
@codemonsieur Gotcha, thanks for the great overview.

I completely agree that it'd be better to expose all of node-sass's options directly to the users! What would you think about passing all of the metalsmith-sass options directly to node-sass, instead of using a nested object for the node-sass options?

I'm curious about the indented syntax you mentioned. I was under the impression that libsass only supports the `.scss` syntax, and not the `.sass` syntax. Has that changed? Or were you talking about something completely different (if so, sorry that I misunderstood)

**Comment by codemonsieur** [comment]
@stevenschobert Welcome!

To be honest, I never looked directly at libsass docs, just referred to node-sass' readme, which did contain the `indentedSyntax` option - so I coded for that :) And yes, I did mean `sass` vs `scss` as in:

```sass
=tint
  background-color: blue

body
   position: relative
   +tint
```
versus
```scss
@mixin tint {
  background-color: blue;
}

body {
  position: relative;
  @include tint;
}
```

I guess that if we threw all of the metalsmith-sass' options at node, it should be fine. The invalid/unrecognized options will just be ignored, am I right? It would, indeed, reduce the number of lines and prob improve speed, should a project have a massive amounts of files to render.

**Comment by stevenschobert** [comment]
Hey @codemonsieur. I'm sorry I let this sit out here so long :( I've been really busy with other projects.

I just pushed out [v1.0](https://github.com/stevenschobert/metalsmith-sass/releases/v1.0.0), that includes the ability to pass through any options to node-sass, so `indentedSyntax` should be supported now, provided that your files still have the `.scss` extension,

Please give it a try and let me know if you have any issues.

**Pull request closed without merging**
