### PR TITLE
Bump node-sass@v4.0.0

### PR DESCRIPTION
**Pull request by shouze**
Even if the major has been incremented, it's BC with v3.13.1 as explained in the [release notes](https://github.com/sass/node-sass/releases/tag/v4.0.0).

### CODE REVIEW

**Comment by MikaFima** [comment]
:+1:

**Comment by shouze** [comment]
@stevenschobert I also have made this commit (and use my fork ATM) https://github.com/shouze/metalsmith-sass/commit/6a4a879f787bb7bfd07f3bde739a4fadd1c1dfe8 because of some issues that can occur with node-sass >= 4.0.0 see https://github.com/sass/node-sass/issues/1669#issuecomment-250712506

**Comment by stevenschobert** [comment]
@shouze Oh interesting. Are you seeing that issue a lot, or just one particular edge case? I skimmed through the thread but curious what your experience with it was.

If there are issues with 4.0.0, it might be better to wait for a couple patches to be out before updating metalsmith-sass.

**Comment by shouze** [comment]
@stevenschobert this occurs everytime on the app I've upgraded so yes it probably worth to wait... or use renderSync like in the commit I've done.

**Comment by xzyfer** [comment]
Heads up fix for the node-sass issues with land in 4.2.0 in the next 48 hours.

**Comment by stevenschobert** [comment]
Oh awesome @xzyfer! Thanks for the heads up (and all the hard work you do on libsass and node-sass, and everything else. Seriously! 🍻)

**Comment by xzyfer** [comment]
<3 thanks @stevenschobert

**Comment by xzyfer** [comment]
node-sass@v4.2.0 was released a couple hours ago. It should resolve this issue.

**Comment by shouze** [comment]
@xzyfer I've just seen, that, testing again with `render` instead of `renderSync` to ensure everything is ok ;)

**Comment by xzyfer** [comment]
I'm jumping into bed now. I'll check back for updates in the morning.

**Comment by shouze** [comment]
@xzyfer it's perfectly working, thx for the great work! ping @stevenschobert so it's ok to merge from this time ;)

**Comment by stevenschobert** [comment]
Thanks everyone, will have this merged in shortly!

**Comment by shouze** [comment]
@stevenschobert 👍  can't wait fot the new tagged release! 👼 

Do you want some help on this repo to have:
- a travis build matrix with various nodejs releases
- not install a gcc/build toolchain anymore as node-sass now bring binaries for most environments?

**Comment by stevenschobert** [comment]
Release is up! [v1.4.0](https://github.com/stevenschobert/metalsmith-sass/releases/tag/v1.4.0)

Let me know if anyone has issues with it!

**Comment by stevenschobert** [comment]
@shouze For the travis build with multiple node versions, I'd love to see a PR! That'd be great.

For using binaries, what did you have in mind? Might want to open up a separate issue on it so we can talk it out first.

**Comment by shouze** [comment]
@stevenschobert sorry... but yes still having some random issues @xzyfer I can try to bring you some app that fail if you want, this is the same old `stack level too deep` error, I just have it less frequently.

@stevenschobert about binaries, this is just that every node-sass release bring binary binding that are downloaded during node-sass install so it's not required anymore for supported node releases & platforms to compile node-sass anymore in fact.

**Comment by xzyfer** [comment]
@shouze sorry I don't follow. Are you saying you're still experiencing issues with stack level too deep? If so please file an issue with node-sass with a reproduction. It's entirely possible you're actually violating the maximum stack depth of 500.

**Comment by shouze** [comment]
@xzyfer yes that's it and yes, probably violating the maximum stack depth of 500 (unfortunately the error occurs on a static website generation that uses one the the latest bootstrap alpha releases).

I'll open a new issue ASAP, my turn to go to bed for now.

**Comment by xzyfer** [comment]
Interesting. I'll try compiling the bootstrap alpha release tonight. I can't imagine they're exceeding the limit without them noticing until now. It's likely the combination of mixins being used.

**Pull request merged**
